FROM debian
RUN apt-get update && apt-get install -y \
        bash \
        curl \
        ethtool \
        gawk \
        net-tools \
        nicstat \
        procps \
        systemd \
        tcpdump \
        trace-cmd \
        && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /run/systemd
COPY ftrace.sh /ftrace.sh
ENTRYPOINT ["/ftrace.sh"]